version: '3.9'

services:

  django:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14.3-alpine3.16
    ports:
      - "5431:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=chatuser
      - POSTGRES_PASSWORD=G6edopcmS8mwKDJ
      - POSTGRES_DB=chatdb

  redis:
    image: redis:5
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    
    ports:
      - "6379:6379"

    volumes: 
      - ./redis:/data